server:
  port: 8081
  servlet:
    context-path: /template

spring:
  application:
    name: eureka-client-coupon-template
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/coupon?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 8
      minimum-idle: 4
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 45000
      auto-commit: true
      pool-name: CouponHikariCP
  redis:
    database: 0
    host: ${REDIS_HOST}
    port: ${REDIS_PORT:6379}
    # password:
    timeout: 10000

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_URL:127.0.0.1}:8000/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: coupon-template
    groupId: coupon-service
    artifactId: coupon-template
    version: 1.0-SNAPSHOT

logging:
  level:
    com.yinghan.coupon: info
