spring:
  application:
    name: coupon-eureka

server:
  port: 8000

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    # get registry info from eureka server or not. since we have only one node, then set to false (no need to sync from others)
    fetch-registry: false
    # if register myself to eureka server or not.
    register-with-eureka: false
    # eureka server running location
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/